### ISSUE TITLE
Code Review - 13 Feb 2019

### ISSUE THREAD

**Issue by GAaronAlexander** [GAaronAlexander/pblh-recalc#1]
Hey Everyone!

Here is my code for review. It is a series of scripts that I have created to help re-calculate the planetary boundary layer height given a WRF output file (or files!) for my work! I have designed it in a way that would allow me to transfer this repository to the Cheyenne supercomputer and to analyze results, as well as work locally if needed. 

***NOTE**** to run this, you need to have a wrfout file. I have provided a small wrfout file in the lab box folder `example_wrf_file`. I know that this is annoying (sorry)!!!

For this review, I would love it for comments on:
1. Do you as a user understand how to run the code and what is going on? Specifically, were the comments at the beginning of each function helpful in outlining what was happening (I am going to be using this in a WRF tutorial at UNR over the summer and getting the style down will be helpful)

2. Are there any issues with coding syntax that can improve speed of the code running? 

3. Was it clear what files were created and where they were stored?

4. General things that can be improved upon. 

Thanks you guys! Have a great week!

Aaron A.

**Comment by jdherman** [comment]
1. What is going on, as far as I know: there are some 4D matrices full of numbers, and we would like to find the height at which a certain threshold value is crossed. This will result in a 2D map at each timestep because the boundary layer height is different at every spatial grid cell.

The commenting is great, and it helps that WRF output data seems to already be in a standardized format, so you can assume some background knowledge there.

Took a minute to install the dependencies (cartopy and wrf-python specifically). I tried with pip at first and it didn't work, you could put in the readme to use conda-forge instead. Eventually I realized you should also install netCDF4 from conda-forge to make everything compatible (this may only be a OSX issue.....). 

So ... my fault. I didn't actually run anything. But I'll suggest some discussion points for 2.

2. Finding the critical height involves looping over 4 dimensions (x,y,z,t) and saving the result to a new array. Let's brainstorm as a group how this could be done with boolean indexing and numpy functions, I bet it will be much faster. 

In my opinion this is THE thing to improve. I couldn't run the profiler but I think this will help a lot especially when you scale it up to larger datasets.

We had talked about this a bit, but there should be a way to use np.argmax with the boolean array along the Z axis.
https://stackoverflow.com/questions/16243955/numpy-first-occurrence-of-value-greater-than-existing-value

So if you have matrix M that has dimensions `nx, ny, nz, nt` and you run:
```python
ix = np.argmax(M > critical_whatever, axis=2) # 2 for the z-dimension
```
then `ix` will be a `nx, ny, nt` matrix containing the index along the z-dimension where the critical value is first exceeded. 

Here's an example that I'm 90% sure is doing the right thing.
```python
import numpy as np 

n = 3 # dimension that we aren't searching over
M = np.random.rand(n, n, 100)

# ix is a 3x3 matrix of indices
ix = np.argmax(M > 0.9, axis=2)

# check all first values M > 0.9 in a loop: (slow way)
for i in range(n):
  for j in range(n):
    print(M[i,j,ix[i,j]])

# OR do this to avoid loops (faster I think/hope way)
xy = np.indices((n,n))
values = M[xy[0].flatten(), xy[1].flatten(), ix.flatten()].reshape(n,n)
print(values)
```
except I'm not convinced it's actually faster. you'd have to try it with some larger datasets. But either way it still avoids the loop over the vertical dimension which should help.

PS eventually I got the packages installed. The extraction runs great. I ran into an error in the plotting though which is too long to copy here, I have no idea what happened. Probably an OSX issue though and nothing you did.

```

**Comment by njmolla** [comment]
•	I had trouble installing the libraries, so I did not run (sorry!)
•	I like how things were broken up into functions and how in the main script, you point to which file contains the function being used (I think that’s a good compromise for using star imports)
•	I find the comments you have helpful and clear. I think the one thing that would’ve helped me is just being more explicit about the dimensions of all the variables you’re working with (like what Jon said above about going from 4-d matrix to a 3d matrix/a 2d matrix per time step) would be helpful since I think that’s the most confusing part.
•	I think it would be good to have the warning about the temperature gradient method being only valid for afternoon values in the main script (since presumably this is where they would turn off that option? Is it meant to be an option?)
•	Sorry, I have nothing to add in terms of improving the speed, my suggestion would’ve been the slower triple loop option but Jon’s way seems better
•	I think your README does a good job explaining the outputs, though I think it would be good if you noted that the number of plots being made is the number of time steps since it might not be immediately obvious

**Comment by brobinson3** [comment]
1. I was initially confused about the wrf_directory and file_name inputs. It seemed like the file_name was already completed, so I wasn’t sure if I should change the wrf_directory (I figured out I needed to pretty quickly though). The code itself is cleanly written and easy to understand what’s going where. The comments are all helpful too. I liked that it was so easy for me to track errors through different scripts and find out exactly what was going wrong where.
2. We already discussed the issues with running it: the file_name line, the single_netcdf_file path, and needing TeX to save the plots. Once those were fixed, it ran fine.
3. Yes! This was very clear. On this note, I think there’s another way to make new folders that doesn’t give a warning/error when the folder is already there: os.makedirs(path, exist_ok=True).
4. Other than fixing the errors, I think you may be able to simplify the area of the script where the user changes/defines strings, keeping that part separate from everything else. There’s not much else I can see to improve on. The whole code is commented well and allowed me to understand what was going on and what was going where even though I’m not familiar with the physics or principles behind what you’re doing. Great work! Also, the plots are very pretty.

**Comment by nataliemall** [comment]
-	NetCDF4 was giving me trouble, but the main.py formatting was straightforward and the comments were very clear- I felt like I could follow along easily without having any background knowledge in PBLH equations.  I foreshadow the package dependencies being the biggest issue with running a workshop on this – especially with students new to installation troubleshooting. I also wasn’t sure about glob and whether to install glob2.  
-	Great job with the assertions; I like how they simultaneously give a reader an idea of what the data looks like at that point in the code. 
-	Besides clearer installation guidelines (which I know is super duper no fun), the tool looks very clean and its functions seem understandable to a layperson. Great job, I learned a lot!

**Comment by ekblad** [comment]
Hi aaron!  I spent some time thinking about how to tackle your threshold value problem as we had talked about.  currently don't have a better approach than jon suggested, but i will keep thinking on it!  the way it is coded now seems very robust, as in readable and will do exactly what you think it is doing.  but, it also seems verbose (which doesn't always translate to slow!) - however, in an application like this where speed really does matter, these are important questions to be asking.  that's all i have, code otherwise is very readable and clean!  looks like you put a lot of work in to make it so, and it worked.

**Comment by jscohen4** [comment]
- I didn't end up running the code (packages to took long to load). Code is quite clear and I especially like the layout of the main file. It's very clear what to change, and I like that you put those options at the very beginning of the script. Code is quite clear, as are function names and comments. 

- Again I agree with Jon that the main thing that would be slowing this down is looping over all the dimensions at each time step. I feel like it would be hard to get passed looping over time, but perhaps some indexing could help extracting the other spacial variables. It would be cool if there was also a ways to instead extract a timeseries for the heightsfor each lat and lon, and then sting them all together?
